Use Standard Go program layout
kimanimichael/whitepointinventory pull request #37
Opened 2024-08-09 17:17 UTC by kimanimichael

Guided by [project-layout](https://github.com/golang-standards/project-layout)

2024-08-17 08:39 UTC, rodneyosodo requested changes
It would be a good idea to separate the API from the service logic and repository layers. This is a well-known architectural pattern called Hexagonal Architecture https://dev.to/bagashiz/building-restful-api-with-hexagonal-architecture-in-go-1mij

2024-08-17 08:39 UTC, rodneyosodo commented on .gitignore
>  .idea/
Add new line

2024-08-17 08:39 UTC, rodneyosodo commented on build/build_run.sh
> +build/whitepointinventory
add new line

2024-08-17 08:39 UTC, rodneyosodo commented on cmd/whitepointinventory/whitepointinventory.go
> +
Since this is one binary project you can use `cmd/main.go` rather than `cmd/whitepointinventory/whitepointinventory.go`

2024-08-17 08:39 UTC, rodneyosodo commented on cmd/whitepointinventory/whitepointinventory.go
> +	err = srv.ListenAndServe()
inline error check

```go
if err := srv.ListenAndServer(); err != nil {
```

2024-08-17 08:39 UTC, rodneyosodo commented on docker/Dockerfile
>  FROM alpine:latest
You can use scratch instead of an alpine image

2024-08-17 08:39 UTC, rodneyosodo commented on docker/Dockerfile
>  FROM alpine:latest
Don't copy the env file

2024-08-17 08:39 UTC, rodneyosodo commented on build/build_run.sh
> +rm -rf build/whitepointinventory
It will overwrite no need to remove

2024-08-17 08:39 UTC, rodneyosodo commented on pkg/jsonresponses/json.go
> +package jsonresponses
Not a good package name you can rename it to `internal/api` -> `package api`

2024-08-17 08:39 UTC, rodneyosodo commented on pkg/health/health.go
> +func HandlerHealth(w http.ResponseWriter, r *http.Request) {
Have a look at https://github.com/mszostok/version or https://github.com/nelkinda/health-go then you can create a health endpoint with those values

This is the standard https://datatracker.ietf.org/doc/html/draft-inadarei-api-health-check#section-5

2024-08-19 20:37 UTC, kimanimichael commented on build/build_run.sh
> +rm -rf build/whitepointinventory
The script runs the old binary if there's an error in compilation, which is undesired behaviour for this particular use case. Hence why I remove it.

2024-08-19 20:47 UTC, kimanimichael commented on pkg/jsonresponses/json.go
> +package jsonresponses
I intend the APIs here to be public APIs. What would be a good package name to still have them in the pkg directory?

2024-08-19 21:11 UTC, kimanimichael commented on docker/Dockerfile
>  FROM alpine:latest
Removed.

2024-08-19 21:12 UTC, kimanimichael commented on docker/Dockerfile
>  FROM alpine:latest
Changed to a scratch base image

2024-08-19 21:12 UTC, kimanimichael commented on cmd/whitepointinventory/whitepointinventory.go
> +	err = srv.ListenAndServe()
Implemented

2024-08-19 21:13 UTC, kimanimichael commented on cmd/whitepointinventory/whitepointinventory.go
> +
Done

2024-08-20 08:20 UTC, rodneyosodo commented on pkg/jsonresponses/json.go
> +package jsonresponses
Public you mean people outside the project would import it as a package?

2024-08-20 13:54 UTC, rodneyosodo commented on pkg/jsonresponses/json.go
> +package jsonresponses
The change the name

2024-08-28 20:36 UTC, kimanimichael commented on build/build_run.sh
> +build/whitepointinventory
Done

2024-08-28 20:36 UTC, kimanimichael commented on .gitignore
>  .idea/
Done

2024-10-01 21:39 UTC, rodneyosodo commented
73 commits one PR. Just merge :joy:

2024-10-06 12:11 UTC, kimanimichael commented
> 73 commits one PR. Just merge 😂

Had to refactor entire code-base. I am doing some clean up and then you can re-review. You can just check of all your comments are handled.

2024-10-14 19:30 UTC, kimanimichael commented
> It would be a good idea to separate the API from the service logic and repository layers. This is a well-known architectural pattern called Hexagonal Architecture https://dev.to/bagashiz/building-restful-api-with-hexagonal-architecture-in-go-1mij

Done.

2024-10-14 19:32 UTC, kimanimichael commented on pkg/health/health.go
> +func HandlerHealth(w http.ResponseWriter, r *http.Request) {
Done.

2024-10-19 10:06 UTC, rodneyosodo requested changes

2024-10-19 10:06 UTC, rodneyosodo commented on internal/domain/payments_repository.go
> +package domain
Try and reduce the underscores in file naming. Use DDD where we have different domains farmer, payments, purchases and users

> domain(for example users)
> > api
> > repository
> > > repository.go
> > middleware(if you have any)
> domain(for example user).go (defines the repository and service interface)
> service.go (implements service)

2024-10-19 10:06 UTC, rodneyosodo commented on .golangci.yml
> +# along with this program. If not, see <http://www.gnu.org/licenses/>.
Add this to CI for example https://github.com/rodneyosodo/gophercon-africa-2024/blob/main/.github/workflows/ci.yaml

2024-11-04 18:33 UTC, kimanimichael commented on internal/middleware/middleware_auth.go
> +package middleware
Done

2024-11-07 21:23 UTC, kimanimichael commented on internal/domain/payments_repository.go
> +package domain
Done @rodneyosodo

2024-11-10 21:15 UTC, rodneyosodo requested changes

2024-11-10 21:15 UTC, rodneyosodo commented on internal/middleware/auth.go
> +package middleware
move this to something like `internal/http/auth.go`

2024-11-10 21:15 UTC, rodneyosodo commented on internal/health/httpapi/health_handler.go
> +package httpapi
move this to something like `internal/http/health.go`

2024-11-10 21:15 UTC, rodneyosodo commented on internal/health/httpapi/health_handler.go
> +import (
Group import for more than one importation

2024-11-10 21:15 UTC, rodneyosodo commented on internal/farmers/farmers.go
> +type FarmerService interface {
Make all functions take in context so that it is propagated from the transport layer to the repository layer.

2024-11-10 21:15 UTC, rodneyosodo commented on internal/farmers/farmers.go
> +	CreateFarmer(name string, chickenBalance float64, cashBalance int32) (*Farmer, error)
```suggestion
	CreateFarmer(ctx context.Context, name string, chickenBalance float64, cashBalance int32) (*Farmer, error)
```

2024-11-10 21:15 UTC, rodneyosodo commented on internal/farmers/farmers.go
> +	DeleteFarmerByID(ID uuid.UUID) error
```suggestion
	DeleteFarmerByID(id string) error
```

2024-11-10 21:15 UTC, rodneyosodo commented on internal/farmers/farmers.go
> +	CreateFarmer(name string, chickenBalance float64, cashBalance int32) (*Farmer, error)
will balance go below 0?

2024-11-10 21:15 UTC, rodneyosodo commented on internal/farmers/farmers.go
> +	GetFarmers() ([]Farmer, error)
Return paginated reponse so that when you have a lot of farmers you can iterate over them

```go
type FarmersPage struct {
	Page
	Farmers []Farmer `json:"farmers"`
}

type Page struct{
	Offset uint64 `json:"offset"`
	Total uint64 `json:"total"`
}

```

2024-11-13 20:51 UTC, kimanimichael commented on internal/farmers/farmers.go
> +	CreateFarmer(name string, chickenBalance float64, cashBalance int32) (*Farmer, error)
Yes. In the event of over-payment.

2024-11-18 19:38 UTC, kimanimichael commented on internal/farmers/farmers.go
> +	GetFarmers() ([]Farmer, error)
@rodneyosodo 

Does this apply for all functions or only where I return multiple farmers?

2024-11-27 06:26 UTC, kimanimichael commented on build/build_run.sh
> +rm -rf build/whitepointinventory
Changed to using a Makefile anyway.

2024-11-27 09:22 UTC, kimanimichael commented on internal/middleware/auth.go
> +package middleware
Done

2024-11-27 09:27 UTC, kimanimichael commented on internal/health/httpapi/health_handler.go
> +package httpapi
Done.

2024-11-27 09:27 UTC, kimanimichael commented on internal/health/httpapi/health_handler.go
> +import (
Done

2024-11-27 09:28 UTC, kimanimichael commented on internal/farmers/farmers.go
> +type FarmerService interface {
Done

2024-11-27 09:28 UTC, kimanimichael commented on internal/farmers/farmers.go
> +	CreateFarmer(name string, chickenBalance float64, cashBalance int32) (*Farmer, error)
Done

2024-11-27 09:29 UTC, kimanimichael commented on internal/farmers/farmers.go
> +	GetFarmers() ([]Farmer, error)
Done

2024-11-27 09:31 UTC, kimanimichael commented on internal/farmers/farmers.go
> +	DeleteFarmerByID(ID uuid.UUID) error
What's the reason for this?

2024-11-29 16:02 UTC, kimanimichael commented on pkg/jsonresponses/json.go
> +package jsonresponses
Done

2024-11-29 16:02 UTC, kimanimichael commented on internal/farmers/farmers.go
> +	DeleteFarmerByID(ID uuid.UUID) error
Done

2024-12-09 20:33 UTC, rodneyosodo approved these changes

2025-01-20 20:19 UTC, merged